name: Bug Report
description: Report a bug or issue with Electroblob's Wizardry Redux
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Cast spell '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: input
    id: mod-version
    attributes:
      label: Mod Version
      description: What version of Electroblob's Wizardry Redux are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: What version of Minecraft are you using?
      placeholder: "e.g., 1.20.1"
    validations:
      required: true

  - type: input
    id: forge-version
    attributes:
      label: Forge/Fabric Version
      description: What version of the mod loader are you using?
      placeholder: "e.g., Forge 47.2.0"
    validations:
      required: true

  - type: textarea
    id: other-mods
    attributes:
      label: Other Mods Installed
      description: List any other mods you have installed that might be relevant
      placeholder: List other mods...
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Crash Report / Logs
      description: Please copy and paste any relevant log output or crash reports
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots
      placeholder: Any additional information...
    validations:
      required: false
